baseURL = "https://dmaulikr.github.io/hounted-secrets-blog/"
title = "Hounted Secrets"
languageCode = "en-us"
enableRobotsTXT = true
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  env = "production"
  description = "Daily doses of horror, suspense & mystery."
  ShowReadingTime = true
  defaultTheme = "dark"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
