baseURL="https://dmaulikr.github.io/hounted-secrets-blog/"
title="Hounted Secrets"
languageCode="en-us"
enableRobotsTXT=true
theme="PaperMod"

[params.amazon]
  tag = "dmaulikr-21"
[[menu.main]]
  name = "Reviews"
  url  = "/reviews/"
  weight = 20
