name: Review-Generator
permissions: { contents: write }
on:
  push:                       # ← new: run when these files change
    branches: [ main ]
    paths:
      - 'data/reviews.csv'
      - '.github/scripts/generate_reviews.py'
      - 'templates/**'
  workflow_dispatch:        # run manually from the Actions tab
  schedule:
    - cron: '0 2 * * *'     # 07:30 IST every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install openai==0.28.1

      - name: Generate reviews from CSV with AI
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        run: .github/scripts/generate_reviews.py

      - name: Commit any new posts
        run: |
          git config user.name "Auto Review Bot"
          git config user.email "bot@users.noreply.github.com"
          git add content/reviews
          git diff --cached --quiet || git commit -m "Auto-generated reviews with AI"

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

